name: Build and Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1
      with:
        vulkan_version: latest
        optional_components: com.lunarg.vulkan.vma
        install_runtime: true
        cache: true
        stripdown: true
        install_swiftshader: true
        install_lavapipe: true
      
    - name: Install Ninja (Windows)
      if: runner.os == 'Windows'
      run: choco install ninja

    - name: Configure CMake
      run: >
        cmake -S . -B build 
        -DSTRICT_COMPILE=ON
        -DCMAKE_BUILD_TYPE=Release
        -G "Ninja"

    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      if: runner.os != 'macOS'
      run: cmake --build build --config Release --target check